/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.UI;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import trabalho.armazenamento.Armazenamento;
import trabalho.modeloDeDados.Configuracao;
import trabalho.modeloDeDados.Controle;
import trabalho.modeloDeDados.VeiculoImportado;
import trabalho.modeloDeDados.VeiculoNacional;

/**
 *
 * @author gabri
 */
public class FrameCadastroVeiculo extends javax.swing.JFrame {
    Controle controleVeiculo = new Controle();
    /**
     * Creates new form Frame_cadastro_veiculo_nacional
     */
    public FrameCadastroVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CadastroVeiculoNacionalModelo = new javax.swing.JTextField();
        CadastroVeiculoNacionalCodigo = new javax.swing.JTextField();
        CadastroVeiculoNacionalMontadora = new javax.swing.JTextField();
        CadastroVeiculoNacionalAnoFabricacao = new javax.swing.JTextField();
        CadastroVeiculoCacionalCategoria = new javax.swing.JTextField();
        CadastroVeiculoNacionalPlaca = new javax.swing.JTextField();
        CadastroVeiculoNacionalFipe = new javax.swing.JTextField();
        btnCadastroVeiculoNacional = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CadastroVeiculoNacionalImpostoEstadual = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CadastroVeiculoNacionalImpostoFederal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnVeiculoInternacional = new javax.swing.JButton();
        TextFieldLucro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de veiculos");

        jLabel1.setText("Modelo do veículo:");

        jLabel2.setText("Codigo do veículo:");

        jLabel3.setText("Montadora:");

        jLabel4.setText("Ano de fabricação:");

        jLabel6.setText("Placa:");

        jLabel7.setText("Categoria:");

        jLabel8.setText("Valor Fipe:");

        CadastroVeiculoNacionalCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroVeiculoNacionalCodigoActionPerformed(evt);
            }
        });

        btnCadastroVeiculoNacional.setText("Cadastrar Veículo nacional");
        btnCadastroVeiculoNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroVeiculoNacionalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Dados de cadastro de veículos");

        jLabel13.setText("Somente para veículos internacionais");

        jLabel14.setText("% imposto estadual:");

        jLabel16.setText("% imposto federal:");

        btnVeiculoInternacional.setText("Cadastrar Veículo Internacional");
        btnVeiculoInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculoInternacionalActionPerformed(evt);
            }
        });

        jLabel17.setText("% Lucro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(CadastroVeiculoNacionalImpostoFederal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CadastroVeiculoNacionalCodigo)
                                    .addComponent(CadastroVeiculoNacionalModelo)
                                    .addComponent(CadastroVeiculoNacionalMontadora)
                                    .addComponent(CadastroVeiculoNacionalAnoFabricacao)
                                    .addComponent(CadastroVeiculoNacionalImpostoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CadastroVeiculoNacionalFipe, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(CadastroVeiculoNacionalPlaca)
                                    .addComponent(CadastroVeiculoCacionalCategoria)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldLucro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnCadastroVeiculoNacional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnVeiculoInternacional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CadastroVeiculoNacionalModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CadastroVeiculoCacionalCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CadastroVeiculoNacionalCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CadastroVeiculoNacionalPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CadastroVeiculoNacionalMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CadastroVeiculoNacionalFipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CadastroVeiculoNacionalAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(TextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CadastroVeiculoNacionalImpostoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroVeiculoNacional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroVeiculoNacionalImpostoFederal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnVeiculoInternacional, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroVeiculoNacionalCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroVeiculoNacionalCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroVeiculoNacionalCodigoActionPerformed

    private void btnCadastroVeiculoNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroVeiculoNacionalActionPerformed
        String modelo = CadastroVeiculoNacionalModelo.getText();
        int codigo = Integer.parseInt(CadastroVeiculoNacionalCodigo.getText());
        String montadora = CadastroVeiculoNacionalMontadora.getText();
        int anoFab = Integer.parseInt(CadastroVeiculoNacionalAnoFabricacao.getText());
        boolean alugado = false;
        String categoria = CadastroVeiculoCacionalCategoria.getText();
        String placa = CadastroVeiculoNacionalPlaca.getText();
        float fipe = Float.parseFloat( CadastroVeiculoNacionalFipe.getText());
        float impostoEstadual = Float.parseFloat(CadastroVeiculoNacionalImpostoEstadual.getText())/100.0f;
        float lucro = Float.parseFloat(TextFieldLucro.getText())/100.0f;
        VeiculoNacional teste = new VeiculoNacional(impostoEstadual, codigo, modelo, montadora, anoFab, placa, categoria, fipe, alugado, lucro);
        controleVeiculo.adicionarVeiculo(teste);
        controleVeiculo.salvarVeiculos();
    }//GEN-LAST:event_btnCadastroVeiculoNacionalActionPerformed

    private void btnVeiculoInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculoInternacionalActionPerformed
        // VeiculoImportado(float taxaImpostoEstadual, float taxaImpostoFederal, int codigoVeiculo, String nomeModelo, String montadora, int anoFabricacao, String placa, String categoria, float valorFipe, float valorDiaria, boolean alugado, float taxaLucro) {
        String modelo = CadastroVeiculoNacionalModelo.getText();
        int codigo = Integer.parseInt(CadastroVeiculoNacionalCodigo.getText());
        String montadora = CadastroVeiculoNacionalMontadora.getText();
        int anoFab = Integer.parseInt(CadastroVeiculoNacionalAnoFabricacao.getText());
        boolean alugado = false;
        String categoria = CadastroVeiculoCacionalCategoria.getText();
        String placa = CadastroVeiculoNacionalPlaca.getText();
        float fipe = Float.parseFloat( CadastroVeiculoNacionalFipe.getText());
        float impostoEstadual = Float.parseFloat(CadastroVeiculoNacionalImpostoEstadual.getText())/100.0f;
        float lucro = Float.parseFloat(TextFieldLucro.getText())/100.0f;
        float ImpostoFederal = Float.parseFloat(CadastroVeiculoNacionalImpostoFederal.getText())/100.0f;
        //VeiculoImportado(float taxaImpostoEstadual, float taxaImpostoFederal, int codigoVeiculo, String nomeModelo, String montadora, int anoFabricacao, String placa, String categoria, float valorFipe, float valorDiaria, boolean alugado, float taxaLucro) {
        VeiculoImportado teste = new VeiculoImportado(ImpostoFederal, impostoEstadual, codigo, modelo, montadora, anoFab, placa, categoria, fipe, alugado, lucro);
        controleVeiculo.adicionarVeiculo(teste);
        controleVeiculo.salvarVeiculos();
    }//GEN-LAST:event_btnVeiculoInternacionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadastroVeiculoCacionalCategoria;
    private javax.swing.JTextField CadastroVeiculoNacionalAnoFabricacao;
    private javax.swing.JTextField CadastroVeiculoNacionalCodigo;
    private javax.swing.JTextField CadastroVeiculoNacionalFipe;
    private javax.swing.JTextField CadastroVeiculoNacionalImpostoEstadual;
    private javax.swing.JTextField CadastroVeiculoNacionalImpostoFederal;
    private javax.swing.JTextField CadastroVeiculoNacionalModelo;
    private javax.swing.JTextField CadastroVeiculoNacionalMontadora;
    private javax.swing.JTextField CadastroVeiculoNacionalPlaca;
    private javax.swing.JTextField TextFieldLucro;
    private javax.swing.JButton btnCadastroVeiculoNacional;
    private javax.swing.JButton btnVeiculoInternacional;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
