/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.UI;
import trabalho.modeloDeDados.Controle;
import trabalho.modeloDeDados.Locacao;
import trabalho.modeloDeDados.Seguro;
/**
 *
 * @author gabri
 */
public class Frame_locacoes extends javax.swing.JFrame {
    Controle controle = new Controle();
    /**
     * Creates new form Frame_locacoes
     */
    public Frame_locacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        locacoes_text_field = new javax.swing.JTextField();
        Locacoes_button_locaces_cadastradas = new javax.swing.JButton();
        Locacoes_button_locaces_atraso = new javax.swing.JButton();
        Locacoes_button_locacoes_lucro_mes = new javax.swing.JButton();
        Locacoes_button_locaces_finalizadas = new javax.swing.JButton();
        Locacoes_button_locaces_nao_finalizadas = new javax.swing.JButton();
        Locacoes_button_seguros_cadastrados = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verificação de locações");

        Locacoes_button_locaces_cadastradas.setText("Locações cadastradas");
        Locacoes_button_locaces_cadastradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Locacoes_button_locaces_cadastradasActionPerformed(evt);
            }
        });

        Locacoes_button_locaces_atraso.setText("Locações em atraso");
        Locacoes_button_locaces_atraso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Locacoes_button_locaces_atrasoActionPerformed(evt);
            }
        });

        Locacoes_button_locacoes_lucro_mes.setText("Locações e lucro de um mês");

        Locacoes_button_locaces_finalizadas.setText("Locações finalizadas");
        Locacoes_button_locaces_finalizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Locacoes_button_locaces_finalizadasActionPerformed(evt);
            }
        });

        Locacoes_button_locaces_nao_finalizadas.setText("Locações não finalizadas");
        Locacoes_button_locaces_nao_finalizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Locacoes_button_locaces_nao_finalizadasActionPerformed(evt);
            }
        });

        Locacoes_button_seguros_cadastrados.setText("Seguros cadastrados");
        Locacoes_button_seguros_cadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Locacoes_button_seguros_cadastradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(locacoes_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Locacoes_button_seguros_cadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Locacoes_button_locaces_cadastradas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Locacoes_button_locacoes_lucro_mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Locacoes_button_locaces_atraso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Locacoes_button_locaces_finalizadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Locacoes_button_locaces_nao_finalizadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Locacoes_button_locaces_cadastradas)
                        .addGap(18, 18, 18)
                        .addComponent(Locacoes_button_locaces_atraso)
                        .addGap(18, 18, 18)
                        .addComponent(Locacoes_button_locacoes_lucro_mes)
                        .addGap(18, 18, 18)
                        .addComponent(Locacoes_button_locaces_finalizadas)
                        .addGap(18, 18, 18)
                        .addComponent(Locacoes_button_locaces_nao_finalizadas)
                        .addGap(21, 21, 21)
                        .addComponent(Locacoes_button_seguros_cadastrados))
                    .addComponent(locacoes_text_field))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Locacoes_button_locaces_cadastradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Locacoes_button_locaces_cadastradasActionPerformed
        String locacoes = "";
        for(Locacao locacao: controle.getLocacoes()){
            locacoes += locacao.toString();
        }
        locacoes_text_field.setText(locacoes);
    }//GEN-LAST:event_Locacoes_button_locaces_cadastradasActionPerformed

    private void Locacoes_button_locaces_atrasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Locacoes_button_locaces_atrasoActionPerformed
        String locacoesAtrasadas = "";
        for (Locacao locacao: controle.getLocacoes()){
            if(locacao.verificarAtraso()){
                locacoesAtrasadas += locacao.toString();
            }
        }
        locacoes_text_field.setText(locacoesAtrasadas);
    }//GEN-LAST:event_Locacoes_button_locaces_atrasoActionPerformed

    private void Locacoes_button_locaces_finalizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Locacoes_button_locaces_finalizadasActionPerformed
        String locacoes = "";
        for(Locacao locacao: controle.getLocacoes()){
            if(locacao.isFinalizada()){
                locacoes += locacao.toString();
            }
        }
        locacoes_text_field.setText(locacoes);
    }//GEN-LAST:event_Locacoes_button_locaces_finalizadasActionPerformed

    private void Locacoes_button_locaces_nao_finalizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Locacoes_button_locaces_nao_finalizadasActionPerformed
        String locacoes = "";
        for(Locacao locacao: controle.getLocacoes()){
            if(!locacao.isFinalizada()){
                if(!locacao.verificarAtraso()){
                    locacoes += locacao.toString();
                }
            }
        }
        locacoes_text_field.setText(locacoes);
    }//GEN-LAST:event_Locacoes_button_locaces_nao_finalizadasActionPerformed

    private void Locacoes_button_seguros_cadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Locacoes_button_seguros_cadastradosActionPerformed
        String seguros = "";
        for(Seguro seguro: controle.getSeguros()){
            seguros += seguro.toString();
        }
        locacoes_text_field.setText(seguros);
    }//GEN-LAST:event_Locacoes_button_seguros_cadastradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_locacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_locacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_locacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_locacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_locacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Locacoes_button_locaces_atraso;
    private javax.swing.JButton Locacoes_button_locaces_cadastradas;
    private javax.swing.JButton Locacoes_button_locaces_finalizadas;
    private javax.swing.JButton Locacoes_button_locaces_nao_finalizadas;
    private javax.swing.JButton Locacoes_button_locacoes_lucro_mes;
    private javax.swing.JButton Locacoes_button_seguros_cadastrados;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField locacoes_text_field;
    // End of variables declaration//GEN-END:variables
}
