/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.UI;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import trabalho.modeloDeDados.Controle;
import trabalho.modeloDeDados.Usuario;
/**
 *
 * @author gabri
 */
public class Frame_pessoas extends javax.swing.JFrame {
    Controle controle = new Controle();
    /**
     * Creates new form Frame_pessoas
     */
    public Frame_pessoas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        textPessoas = new javax.swing.JTextField();
        Button_listar_funcionarios = new javax.swing.JButton();
        button_funcionario_mes = new javax.swing.JButton();
        button_clientes_cadastrados = new javax.swing.JButton();
        button_historico_locacao = new javax.swing.JButton();
        button_locacoes_atrasadas = new javax.swing.JButton();
        Mes = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Button_listar_funcionarios.setText("Listar todos funcionários");
        Button_listar_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_listar_funcionariosActionPerformed(evt);
            }
        });

        button_funcionario_mes.setText("Funcionário do mês");
        button_funcionario_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_funcionario_mesActionPerformed(evt);
            }
        });

        button_clientes_cadastrados.setText("Clientes cadastrados");
        button_clientes_cadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clientes_cadastradosActionPerformed(evt);
            }
        });

        button_historico_locacao.setText("Histórico de locação de um cliente");
        button_historico_locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_historico_locacaoActionPerformed(evt);
            }
        });

        button_locacoes_atrasadas.setText("Clientes com locações atrasadas");
        button_locacoes_atrasadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_locacoes_atrasadasActionPerformed(evt);
            }
        });

        jLabel1.setText("Mês:");

        jLabel2.setText("Ano:");

        jLabel3.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_listar_funcionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_funcionario_mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_clientes_cadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_historico_locacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_locacoes_atrasadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(text_cliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPessoas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_listar_funcionarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_funcionario_mes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_clientes_cadastrados)
                        .addGap(18, 18, 18)
                        .addComponent(button_historico_locacao)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(text_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_locacoes_atrasadas)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_listar_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_listar_funcionariosActionPerformed
        String funcionarios = "";
        for(Usuario funcionario: controle.getFuncionarios()){
            funcionarios += funcionario.toString();
        }
        System.out.print(funcionarios);
        textPessoas.setText(funcionarios);
    }//GEN-LAST:event_Button_listar_funcionariosActionPerformed

    private void button_clientes_cadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clientes_cadastradosActionPerformed
        String clientes = "";
        for(Usuario cliente: controle.getClientes()){
            clientes += cliente.toString();
        }
        textPessoas.setText(clientes);
    }//GEN-LAST:event_button_clientes_cadastradosActionPerformed

    private void button_locacoes_atrasadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_locacoes_atrasadasActionPerformed
        String clientes = "";
        for(Usuario cliente: controle.clientesAtrasados()){
            clientes += cliente.toString();
        }
        textPessoas.setText(clientes);
    }//GEN-LAST:event_button_locacoes_atrasadasActionPerformed

    private void button_funcionario_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_funcionario_mesActionPerformed
      
        int data_ano = Integer.parseInt(ano.getText());
        
        int data_mes = Integer.parseInt(Mes.getText());
        
        controle.funcionarioDoMes(data_mes, data_ano);
            
        
        
    }//GEN-LAST:event_button_funcionario_mesActionPerformed

    private void button_historico_locacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_historico_locacaoActionPerformed
        
        String nome_cliente = text_cliente.getText();
        
    }//GEN-LAST:event_button_historico_locacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_pessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_listar_funcionarios;
    private javax.swing.JTextField Mes;
    private javax.swing.JTextField ano;
    private javax.swing.JButton button_clientes_cadastrados;
    private javax.swing.JButton button_funcionario_mes;
    private javax.swing.JButton button_historico_locacao;
    private javax.swing.JButton button_locacoes_atrasadas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField textPessoas;
    private javax.swing.JTextField text_cliente;
    // End of variables declaration//GEN-END:variables
}
