/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.UI;

/**
 *
 * @author gabri
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuVeiculos = new javax.swing.JMenu();
        menuVerificarVeiculos = new javax.swing.JMenuItem();
        menuCadastrarVeiculos = new javax.swing.JMenuItem();
        MenuPessoas = new javax.swing.JMenu();
        menuVerificarUsuarios = new javax.swing.JMenuItem();
        menuCadastrarUsuarios = new javax.swing.JMenuItem();
        MenuLocacoes = new javax.swing.JMenu();
        menu_locacoes_nao_finalizadas = new javax.swing.JMenuItem();
        menu_criar_locacao = new javax.swing.JMenuItem();
        MenuConfig = new javax.swing.JMenu();
        MenuSalvarConfig = new javax.swing.JMenuItem();
        MenuCarregaConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locadora");

        MenuVeiculos.setText("Veículos");

        menuVerificarVeiculos.setText("Verificar veículos");
        menuVerificarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerificarVeiculosActionPerformed(evt);
            }
        });
        MenuVeiculos.add(menuVerificarVeiculos);

        menuCadastrarVeiculos.setText("Cadastrar veículos");
        menuCadastrarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarVeiculosActionPerformed(evt);
            }
        });
        MenuVeiculos.add(menuCadastrarVeiculos);

        jMenuBar1.add(MenuVeiculos);

        MenuPessoas.setText("Pessoas");

        menuVerificarUsuarios.setText("Verificar usuários");
        menuVerificarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerificarUsuariosActionPerformed(evt);
            }
        });
        MenuPessoas.add(menuVerificarUsuarios);

        menuCadastrarUsuarios.setText("Cadastrar usuário");
        menuCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarUsuariosActionPerformed(evt);
            }
        });
        MenuPessoas.add(menuCadastrarUsuarios);

        jMenuBar1.add(MenuPessoas);

        MenuLocacoes.setText("Locações");

        menu_locacoes_nao_finalizadas.setText("Verificar Locações");
        menu_locacoes_nao_finalizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_locacoes_nao_finalizadasActionPerformed(evt);
            }
        });
        MenuLocacoes.add(menu_locacoes_nao_finalizadas);

        menu_criar_locacao.setText("Criar locação");
        menu_criar_locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_criar_locacaoActionPerformed(evt);
            }
        });
        MenuLocacoes.add(menu_criar_locacao);

        jMenuBar1.add(MenuLocacoes);

        MenuConfig.setText("Configurações");
        MenuConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConfigActionPerformed(evt);
            }
        });

        MenuSalvarConfig.setText("Salvar configuração");
        MenuSalvarConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalvarConfigActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuSalvarConfig);

        MenuCarregaConfig.setText("Carregar configuração");
        MenuCarregaConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCarregaConfigActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuCarregaConfig);

        jMenuBar1.add(MenuConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarUsuariosActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroUsuario().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_menuCadastrarUsuariosActionPerformed

    private void menuVerificarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerificarVeiculosActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVeiculos().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuVerificarVeiculosActionPerformed

    private void menuCadastrarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarVeiculosActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroVeiculo().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuCadastrarVeiculosActionPerformed

    private void menuVerificarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerificarUsuariosActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePessoas().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuVerificarUsuariosActionPerformed

    private void menu_criar_locacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_criar_locacaoActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroLocacao().setVisible(true);
            }
        });
    }//GEN-LAST:event_menu_criar_locacaoActionPerformed

    private void menu_locacoes_nao_finalizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_locacoes_nao_finalizadasActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLocacoes().setVisible(true);
            }
        });
    }//GEN-LAST:event_menu_locacoes_nao_finalizadasActionPerformed

    private void MenuConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConfigActionPerformed
        
    }//GEN-LAST:event_MenuConfigActionPerformed

    private void MenuSalvarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalvarConfigActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSalvarConfig().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuSalvarConfigActionPerformed

    private void MenuCarregaConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCarregaConfigActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCarregarConfig().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuCarregaConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCarregaConfig;
    private javax.swing.JMenu MenuConfig;
    private javax.swing.JMenu MenuLocacoes;
    private javax.swing.JMenu MenuPessoas;
    private javax.swing.JMenuItem MenuSalvarConfig;
    private javax.swing.JMenu MenuVeiculos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadastrarUsuarios;
    private javax.swing.JMenuItem menuCadastrarVeiculos;
    private javax.swing.JMenuItem menuVerificarUsuarios;
    private javax.swing.JMenuItem menuVerificarVeiculos;
    private javax.swing.JMenuItem menu_criar_locacao;
    private javax.swing.JMenuItem menu_locacoes_nao_finalizadas;
    // End of variables declaration//GEN-END:variables
}
