/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.UI;
import trabalho.modeloDeDados.Controle;
import trabalho.modeloDeDados.Locacao;
import trabalho.modeloDeDados.Seguro;
/**
 *
 * @author gabri
 */
public class FrameLocacoes extends javax.swing.JFrame {
    Controle controle = new Controle();
    /**
     * Creates new form Frame_locacoes
     */
    public FrameLocacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        LocacoesButtonLocacesCadastradas = new javax.swing.JButton();
        LocacoesButtonLocacesAtraso = new javax.swing.JButton();
        LocacoesButtonLocacoesLucroMes = new javax.swing.JButton();
        LocacoesButtonLocacesFinalizadas = new javax.swing.JButton();
        LocacoesButtonLocacesNaoFinalizadas = new javax.swing.JButton();
        LocacoesButtonSegurosCadastrados = new javax.swing.JButton();
        TextFieldAno = new javax.swing.JTextField();
        TextFieldMes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        locacoesTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verificação de locações");

        LocacoesButtonLocacesCadastradas.setText("Locações cadastradas");
        LocacoesButtonLocacesCadastradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocacoesButtonLocacesCadastradasActionPerformed(evt);
            }
        });

        LocacoesButtonLocacesAtraso.setText("Locações em atraso");
        LocacoesButtonLocacesAtraso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocacoesButtonLocacesAtrasoActionPerformed(evt);
            }
        });

        LocacoesButtonLocacoesLucroMes.setText("Locações e lucro de um mês");
        LocacoesButtonLocacoesLucroMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocacoesButtonLocacoesLucroMesActionPerformed(evt);
            }
        });

        LocacoesButtonLocacesFinalizadas.setText("Locações finalizadas");
        LocacoesButtonLocacesFinalizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocacoesButtonLocacesFinalizadasActionPerformed(evt);
            }
        });

        LocacoesButtonLocacesNaoFinalizadas.setText("Locações não finalizadas");
        LocacoesButtonLocacesNaoFinalizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocacoesButtonLocacesNaoFinalizadasActionPerformed(evt);
            }
        });

        LocacoesButtonSegurosCadastrados.setText("Seguros cadastrados");
        LocacoesButtonSegurosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocacoesButtonSegurosCadastradosActionPerformed(evt);
            }
        });

        jLabel1.setText("Ano");

        jLabel2.setText("Mês");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Relatório de locações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(locacoesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocacoesButtonLocacesCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocacoesButtonLocacesAtraso, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocacoesButtonLocacesFinalizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocacoesButtonLocacesNaoFinalizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocacoesButtonSegurosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(TextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LocacoesButtonLocacoesLucroMes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LocacoesButtonLocacesCadastradas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocacoesButtonLocacesAtraso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocacoesButtonLocacesFinalizadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocacoesButtonLocacesNaoFinalizadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocacoesButtonSegurosCadastrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocacoesButtonLocacoesLucroMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(locacoesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocacoesButtonLocacesCadastradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocacoesButtonLocacesCadastradasActionPerformed
        String locacoes = "";
        for(Locacao locacao: controle.getLocacoes()){
            locacoes += locacao.toString();
        }
        locacoesTextField.setText(locacoes);
    }//GEN-LAST:event_LocacoesButtonLocacesCadastradasActionPerformed

    private void LocacoesButtonLocacesAtrasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocacoesButtonLocacesAtrasoActionPerformed
        String locacoesAtrasadas = "";
        for (Locacao locacao: controle.getLocacoes()){
            if(locacao.verificarAtraso()){
                locacoesAtrasadas += locacao.toString();
            }
        }
        locacoesTextField.setText(locacoesAtrasadas);
    }//GEN-LAST:event_LocacoesButtonLocacesAtrasoActionPerformed

    private void LocacoesButtonLocacesFinalizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocacoesButtonLocacesFinalizadasActionPerformed
        String locacoes = "";
        for(Locacao locacao: controle.getLocacoes()){
            if(locacao.isFinalizada()){
                locacoes += locacao.toString();
            }
        }
        locacoesTextField.setText(locacoes);
    }//GEN-LAST:event_LocacoesButtonLocacesFinalizadasActionPerformed

    private void LocacoesButtonLocacesNaoFinalizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocacoesButtonLocacesNaoFinalizadasActionPerformed
        String locacoes = "";
        for(Locacao locacao: controle.getLocacoes()){
            if(!locacao.isFinalizada()){
                if(!locacao.verificarAtraso()){
                    locacoes += locacao.toString();
                }
            }
        }
        locacoesTextField.setText(locacoes);
    }//GEN-LAST:event_LocacoesButtonLocacesNaoFinalizadasActionPerformed

    private void LocacoesButtonSegurosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocacoesButtonSegurosCadastradosActionPerformed
        String seguros = "";
        for(Seguro seguro: controle.getSeguros()){
            seguros += seguro.toString();
        }
        locacoesTextField.setText(seguros);
    }//GEN-LAST:event_LocacoesButtonSegurosCadastradosActionPerformed

    private void LocacoesButtonLocacoesLucroMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocacoesButtonLocacoesLucroMesActionPerformed
        
        int ano = Integer.parseInt(TextFieldAno.getText());
        
        String mes = TextFieldMes.getText();
    }//GEN-LAST:event_LocacoesButtonLocacoesLucroMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLocacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LocacoesButtonLocacesAtraso;
    private javax.swing.JButton LocacoesButtonLocacesCadastradas;
    private javax.swing.JButton LocacoesButtonLocacesFinalizadas;
    private javax.swing.JButton LocacoesButtonLocacesNaoFinalizadas;
    private javax.swing.JButton LocacoesButtonLocacoesLucroMes;
    private javax.swing.JButton LocacoesButtonSegurosCadastrados;
    private javax.swing.JTextField TextFieldAno;
    private javax.swing.JTextField TextFieldMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField locacoesTextField;
    // End of variables declaration//GEN-END:variables
}
