/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_pratico_1;

/**
 *
 * @author gabri
 */
public class Frame_principal extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_verificar_veiculos = new javax.swing.JMenuItem();
        menu_cadastrar_veiculos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_verificar_usuarios = new javax.swing.JMenuItem();
        menu_cadastrar_usuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_locacoes_verificar = new javax.swing.JMenuItem();
        menu_criar_locacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1337");

        jMenu1.setText("Veiculos");

        menu_verificar_veiculos.setText("Verificar veiculos");
        menu_verificar_veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_verificar_veiculosActionPerformed(evt);
            }
        });
        jMenu1.add(menu_verificar_veiculos);

        menu_cadastrar_veiculos.setText("Cadastrar Veiculos");
        menu_cadastrar_veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrar_veiculosActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cadastrar_veiculos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pessoas");

        menu_verificar_usuarios.setText("Verificar usuarios");
        menu_verificar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_verificar_usuariosActionPerformed(evt);
            }
        });
        jMenu2.add(menu_verificar_usuarios);

        menu_cadastrar_usuarios.setText("Cadastrar usuário");
        menu_cadastrar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrar_usuariosActionPerformed(evt);
            }
        });
        jMenu2.add(menu_cadastrar_usuarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Locações");

        menu_locacoes_verificar.setText("Verificer locações");
        menu_locacoes_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_locacoes_verificarActionPerformed(evt);
            }
        });
        jMenu3.add(menu_locacoes_verificar);

        menu_criar_locacao.setText("Criar locação");
        menu_criar_locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_criar_locacaoActionPerformed(evt);
            }
        });
        jMenu3.add(menu_criar_locacao);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_locacoes_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_locacoes_verificarActionPerformed
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_locacoes().setVisible(true);
            }
        });
    }//GEN-LAST:event_menu_locacoes_verificarActionPerformed

    private void menu_cadastrar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrar_usuariosActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_cadastro_usuario().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_menu_cadastrar_usuariosActionPerformed

    private void menu_verificar_veiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_verificar_veiculosActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_veiculos().setVisible(true);
            }
        });
    }//GEN-LAST:event_menu_verificar_veiculosActionPerformed

    private void menu_cadastrar_veiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrar_veiculosActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_cadastro_veiculo().setVisible(true);
            }
        });
    }//GEN-LAST:event_menu_cadastrar_veiculosActionPerformed

    private void menu_verificar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_verificar_usuariosActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_pessoas().setVisible(true);
            }
        });
    }//GEN-LAST:event_menu_verificar_usuariosActionPerformed

    private void menu_criar_locacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_criar_locacaoActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_cadastro_locacao().setVisible(true);
            }
        });
    }//GEN-LAST:event_menu_criar_locacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_cadastrar_usuarios;
    private javax.swing.JMenuItem menu_cadastrar_veiculos;
    private javax.swing.JMenuItem menu_criar_locacao;
    private javax.swing.JMenuItem menu_locacoes_verificar;
    private javax.swing.JMenuItem menu_verificar_usuarios;
    private javax.swing.JMenuItem menu_verificar_veiculos;
    // End of variables declaration//GEN-END:variables
}
